--------------------
2018-08-24 16:24:26 - Exception on message: <karelia.Packet object at 0x7fcc8449fda0>:
Traceback (most recent call last):
  File "main.py", line 174, in <module>
    saved_rolls = get_saved_rolls()
  File "main.py", line 8, in get_saved_rolls
    with open('saved_rolls.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'saved_rolls.json'


--------------------
2018-08-24 16:25:28 - Exception on message: <karelia.Packet object at 0x7ff3f3d0ddd8>:
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    saved_rolls[roll_name] = roll_formula
TypeError: list indices must be integers or slices, not str


